services:
  backend:
    image: ghcr.io/ansh-verma1404/k8s-yaml-analyzer-backend:latest
    container_name: k8s-analyzer-backend
    ports:
      - "8443:8443"   # backend actually runs on port 8443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - analyzer-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: k8s-analyzer-frontend
    ports:
      - "8090:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - analyzer-net

networks:
  analyzer-net:
    driver: bridge
