apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer-frontend
  template:
    metadata:
      labels:
        app: analyzer-frontend
    spec:
      containers:
        - name: frontend
          image:  ghcr.io/ansh-verma1404/k8s-yaml-analyzer-frontend:0.1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: analyzer-frontend
spec:
  type: NodePort
  selector:
    app: analyzer-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
