apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer-frontend
  template:
    metadata:
      labels:
        app: analyzer-frontend
    spec:
      containers:
        - name: frontend
          image: k8s-yaml-analyzer-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: analyzer-frontend
spec:
  type: NodePort
  selector:
    app: analyzer-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
