apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer-webhook
  template:
    metadata:
      labels:
        app: analyzer-webhook
    spec:
      containers:
        - name: analyzer-webhook
          image: k8s-yaml-analyzer-backend:0.1.0

          imagePullPolicy: Never
          args:
            - "uvicorn"
            - "k8s_analyzer.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8443"
            - "--ssl-keyfile"
            - "/certs/tls.key"
            - "--ssl-certfile"
            - "/certs/tls.crt"
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: analyzer-webhook-tls
