apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-webhook
  namespace: default
  labels:
    app: analyzer-webhook
    skip-webhook: "true"    # <--- IMPORTANT: do not validate yourself
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer-webhook
  template:
    metadata:
      labels:
        app: analyzer-webhook
        skip-webhook: "true"   # <--- also on pod template
    spec:
      containers:
        - name: analyzer-webhook
          image: ghcr.io/ansh-verma1404/k8s-yaml-analyzer-backend:v20251204-1
          imagePullPolicy: IfNotPresent
          
          args:
            - "uvicorn"
            - "k8s_analyzer.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8443"
            - "--ssl-keyfile"
            - "/certs/tls.key"
            - "--ssl-certfile"
            - "/certs/tls.crt"

          ports:
            - containerPort: 8443
              name: https

          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true

      volumes:
        - name: tls-certs
          secret:
            secretName: analyzer-webhook-tls
