name: K8s YAML Analyzer CI

on:
  push:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Detect modified YAML
      id: detect
      run: |
        FILE=$(git diff --name-only HEAD~1 | grep -E '\.ya?ml$' | head -n 1)
        echo "file=$FILE" >> $GITHUB_OUTPUT
        echo "Detected YAML: $FILE"

    - name: Fail if no YAML found
      run: |
        if [ -z "${{ steps.detect.outputs.file }}" ]; then
          echo "No YAML changed — exiting safely."
          exit 0
        fi

    - name: Run Analyzer
      run: |
        FILE=${{ steps.detect.outputs.file }}
        echo "Scanning file: $FILE"

        docker run --platform linux/amd64 \
          -v ${{ github.workspace }}:/scan \
          ghcr.io/ansh-verma1404/k8s-yaml-analyzer-backend:latest \
          python /app/cli.py /scan/$FILE > findings.json

        echo "--- Analyzer Output ---"
        cat findings.json

    - name: Fail on HIGH or CRITICAL
      run: |
        if grep -q '"HIGH"' findings.json || grep -q '"CRITICAL"' findings.json; then
          echo "❌ Vulnerabilities found — CI FAILED"
          exit 1
        fi
        echo "✔️ No high vulnerabilities — CI PASSED"
