name: K8s YAML Analyzer CI

on:
  push:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Detect modified YAML file
      run: |
        FILE=$(git diff --name-only HEAD~1 | grep -E '\.ya?ml$' | head -n 1)
        echo "TARGET_FILE=$FILE" >> $GITHUB_ENV
        echo "üîç Scanning: $FILE"

    - name: Run analyzer
      run: |
        docker run --platform linux/amd64 \
          -v ${{ github.workspace }}:/scan \
          ghcr.io/ansh-verma1404/k8s-yaml-analyzer-backend:latest \
          python /app/cli.py /scan/${{ env.TARGET_FILE }} > findings.json
        echo "===== Analyzer Output ====="
        cat findings.json

    - name: Fail pipeline if HIGH or CRITICAL exists
      run: |
        if grep -q '"HIGH"' findings.json || grep -q '"CRITICAL"' findings.json; then
          echo "‚ùå High/Critical vulnerabilities detected. Build blocked."
          exit 1
        fi
        echo "‚úîÔ∏è YAML is secure ‚Äî Build approved."
