name: K8s YAML Analyzer CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run analyzer on valid-deployment.yaml
      run: |
        docker run --platform linux/amd64 \
          -v ${{ github.workspace }}:/scan \
          ghcr.io/ansh-verma1404/k8s-yaml-analyzer-backend:latest \
          python /app/cli.py /scan/tests/valid-deployment.yaml > findings.json
        echo "===== Analyzer Output ====="
        cat findings.json

    - name: Fail pipeline if HIGH or CRITICAL exists
      run: |
        CRIT=$(jq '.summary.CRITICAL' findings.json)
        HIGH=$(jq '.summary.HIGH' findings.json)
        if [ "$CRIT" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
          echo "❌ High/Critical vulnerabilities detected. Build blocked."
          exit 1
        fi
        echo "✔️ YAML is secure — Build approved."
