name: K8s YAML Analyzer CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Detect modified YAML file
      id: detect
      run: |
        FILE=$(git diff --name-only HEAD~1 | grep -E '\.ya?ml$' | head -n 1 || true)
        if [ -z "$FILE" ]; then
          echo "No YAML files modified."
          exit 0
        fi
        echo "yaml_file=$FILE" >> $GITHUB_OUTPUT
        echo "Scanning: $FILE"

    - name: Run analyzer
      run: |
        docker run --platform linux/amd64 \
          -v ${{ github.workspace }}:/scan \
          ghcr.io/ansh-verma1404/k8s-yaml-analyzer-backend:latest \
          python /app/cli.py /scan/${{ steps.detect.outputs.yaml_file }} > findings.json
        cat findings.json

    - name: Fail build on HIGH or CRITICAL
      run: |
        if grep -q '"HIGH"' findings.json || grep -q '"CRITICAL"' findings.json; then
          echo "❌ Build blocked — High/Critical vulnerabilities detected."
          exit 1
        fi
        echo "✔️ Build allowed — No high vulnerabilities found."
